stack: python 3.9

branches:
  only:
    - master

image:
  - Ubuntu2004

build: off

install:
  # Install the Twitter bot library dependencies
  - python -m pip install --upgrade pip
  - python -m pip install pillow
  - python -m pip install tweepy

test_script:
  # Attempt to run the bot (expect failure to connect due to bad credentials)
  - cd %APPVEYOR_BUILD_FOLDER%
  - pushd bot
  - python bot.py

# Note that the documentation generation etc are triggered as a post-build script