language: python
os: linux

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pillow
  - pip install tweepy

# Attempt to run the bot (expect failure to connect due to bad credentials)
script:
  - pushd bot
  - python bot.py
  - popd