language: python
os: linux

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pillow
  - pip install tweepy

# Install Travis so we can get the token from Travis
before_script:
  - gem install travis

script:
  # Attempt to run the bot (expect failure to connect due to bad credentials)
  - pushd bot
  - python bot.py || [[ $? -eq 1 ]]
  - popd

# Tell downstream repositories that the Geometrize Twitter bot has been updated
after_script:
  - chmod +x trigger_travis.sh
  # Only run once for the whole build matrix
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then ./trigger_travis.sh Tw1ddle geometrize-twitter-bot-docs master $TRAVIS_ACCESS_TOKEN_GEOMETRIZE_TWITTER_BOT_DOCS_TRIGGER; fi