language: python
os: linux

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pillow
  - pip install tweepy

script:
  # Attempt to run the bot (expect failure to connect due to bad credentials)
  - pushd bot
  - python bot.py || [[ $? -eq 1 ]]
  - popd